name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: GuilleDF/buckaroo-action@v1.0.3
        with: 
          commands: BUCKAROO_USE_BUCK=1 /bin/buckaroo install && buck build //...
